import { Minus, Plus, Search, ShoppingBag, X } from "lucide-react";
import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { categories, demoMenu } from "@/lib/content";
import { useCart } from "@/contexts/cart-context";
import { Link } from "@tanstack/react-router";
const money=(value:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value/100);
export function MenuBrowser({compact=false}:{compact?:boolean}){const [category,setCategory]=useState("Todos");const [query,setQuery]=useState("");const cart=useCart();const filtered=useMemo(()=>demoMenu.filter(item=>(category==="Todos"||item.category===category)&&item.name.toLowerCase().includes(query.toLowerCase())),[category,query]);return <div>
  {!compact&&<div className="relative mb-10 max-w-md"><Search className="absolute left-0 top-1/2 size-4 -translate-y-1/2 text-gold"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Pesquisar no cardápio" aria-label="Pesquisar pratos" className="w-full border-b border-border bg-transparent py-3 pl-7 text-sm outline-none transition-colors focus:border-gold"/></div>}
  <div className="hide-scrollbar mb-10 flex gap-7 overflow-x-auto border-b border-border" role="tablist">{categories.map(cat=><button key={cat} role="tab" aria-selected={category===cat} onClick={()=>setCategory(cat)} className={`shrink-0 border-b py-4 text-xs uppercase tracking-[0.14em] transition-colors ${category===cat?"border-gold text-gold":"border-transparent text-muted-foreground hover:text-foreground"}`}>{cat}</button>)}</div>
  <div className={`grid gap-x-7 gap-y-12 ${compact?"md:grid-cols-3":"md:grid-cols-2 lg:grid-cols-3"}`}>{filtered.slice(0,compact?3:undefined).map(item=><article key={item.id} className="group"><div className="image-reveal aspect-[4/3] overflow-hidden bg-muted"><img src={item.image} alt={`${item.category} — imagem ilustrativa`} width={1200} height={900} loading="lazy" className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-[1.03]"/></div><div className="pt-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[0.18em] text-gold">{item.category} · Demonstração</p><h3 className="mt-2 font-display text-2xl">{item.name}</h3></div><p className="shrink-0 font-medium">{item.price==null?"—":money(item.price)}</p></div><p className="mt-3 text-sm leading-6 text-muted-foreground">{item.description}</p><Button variant="underline" className="mt-4" disabled={item.price==null} onClick={()=>cart.add(item)}>{item.price==null?"Aguardando cadastro":"Adicionar ao pedido"}</Button></div></article>)}</div>
  {compact&&<Button asChild variant="outline" className="mt-12"><Link to="/cardapio">Ver cardápio completo</Link></Button>}
</div>}
export function CartDrawer(){const cart=useCart();return <>{cart.count>0&&<Button variant="gold" className="fixed bottom-5 right-5 z-40 shadow-premium" onClick={()=>cart.setOpen(true)}><ShoppingBag/>Pedido · {cart.count}</Button>}{cart.open&&<div className="fixed inset-0 z-[70] bg-background/70 backdrop-blur-sm" onClick={()=>cart.setOpen(false)}><aside className="absolute right-0 top-0 flex h-full w-full max-w-md flex-col bg-card p-6" onClick={(e)=>e.stopPropagation()}><div className="flex items-center justify-between"><h2 className="font-display text-3xl">Seu pedido</h2><Button variant="ghost" size="icon" onClick={()=>cart.setOpen(false)} aria-label="Fechar carrinho"><X/></Button></div><div className="mt-8 flex-1 space-y-6 overflow-y-auto">{cart.items.length===0?<p className="text-muted-foreground">Seu pedido ainda está vazio.</p>:cart.items.map(item=><div key={item.id} className="flex gap-4 border-b border-border pb-5"><img src={item.image} alt="" className="size-20 object-cover"/><div className="flex-1"><h3 className="font-display text-lg">{item.name}</h3><p className="mt-1 text-sm text-gold">{money(item.price??0)}</p><div className="mt-3 flex items-center gap-3"><Button size="icon-sm" variant="ghost" onClick={()=>cart.change(item.id,item.quantity-1)} aria-label="Diminuir quantidade"><Minus/></Button><span>{item.quantity}</span><Button size="icon-sm" variant="ghost" onClick={()=>cart.change(item.id,item.quantity+1)} aria-label="Aumentar quantidade"><Plus/></Button></div></div></div>)}</div><div className="border-t border-border pt-5"><div className="flex justify-between font-medium"><span>Subtotal</span><span>{money(cart.subtotal)}</span></div><p className="mt-2 text-xs text-muted-foreground">Taxa de entrega calculada após informar o endereço.</p><Button asChild variant="gold" size="lg" className="mt-5 w-full" disabled={!cart.items.length}><Link to="/checkout" onClick={()=>cart.setOpen(false)}>Continuar</Link></Button></div></aside></div>}</>}
